npnt:
  # Informações do blog
  title:        "nepente"
  subtitle:     "Nossas ideias construídas com Jekyll, café e amor"
  cover_image:  blog-cover.jpg
  logo:         logo.png

  # Informações da empresa
  company:      nepente
  url:          http://nepente.io/
  github:       nepente
  twitter:      nepente_io
  gplus:        '106736426804386918228'
  about_link:   /quem-somos.html
  contact_link: /contato.html

  # Comentários
  disqus:
    shortname:  nepente

  # AddThis
  add-this: true

 # Google Analytics
  analytics:
    google: false


  # Google Fonts
  google_font: 'Droid+Sans:400,700'

url:         http://blog.nepente.io
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
timezone:    nil

# Exibição de futuras postagens
future:      false
show_drafts: nil
limit_posts: 0
highlighter: true

relative_permalinks: true

permalink:     pretty
paginate_path: 'page:num'
paginate: 5

markdown:      kramdown
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

gems: [jemoji, font-awesome-less]

excerpt_separator: "<!-- more -->"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     ""
lsi:         false

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true

addthis:
  pubid: ra-54b7473e059fdcaf
  image: /path/to/share/img

# Autores
authors:
  andre:
    name: André Poleza
    twitter: andrepoleza
    bio: Carinha que mora logo ali
    gravatar: ba4840e6419306fdf1c47760e1176133
  diego:
    name: Diego B. Fernandez
    twitter: diegobfernandez
    bio: Carinha que mora logo ali
    gravatar: 8d5b027e01ba424b54b068705a5be232
  felipe:
    name: Felipe Lima
    twitter: limafelipe92
    bio: Carinha que mora logo ali
    gravatar: e9326e57fea793df26fda314ca3bfea6
